---
# defaults file for host_essentials

linux_patching_rv_upgrade_existing_packages: true

linux_patching_rv_install_headers: true

linux_patching_rv_packages:
  - zip
  - unzip
  - net-tools
  - resolvconf
  - build-essential
  - tar
  - wget
  - curl
  - ca-certificates
  - sudo
  - systemd
  - telnet
  - gnupg2
  - apt-transport-https
  - lsb-release
  - software-properties-common
  - locales
  - systemd-timesyncd
  - network-manager
  - gnupg2
  - gnupg
  - pigz
  - cron
  - acl
  - ufw
  - vim
  - git
  - fontconfig
  - gtk-update-icon-cache
  - libnss3
  - libatk1.0-0
  - libatk-bridge2.0-0
  - libgtk-3-0
  - bzip2
  - libgbm-dev
  - libglib2.0-dev
  - libdrm-dev
  - libasound2
  - jq
  - zsh
  - libcap2-bin
  - ntfs-3g
  - exfat-fuse
  - vim
  - neovim
  - python3-venv

linux_patching_rv_timezone: Asia/Kolkata

linux_patching_rv_hostname: "{{ ansible_facts['hostname'] | mandatory }}"
# linux_patching_rv_root_ca_pem_content:

linux_patching_rv_ssh_port: 22
