---
java_rv_jdk_download_url_map:
  17:
    x86_64: https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
    aarch64: https://download.oracle.com/java/17/archive/jdk-17.0.4_linux-aarch64_bin.tar.gz

java_rv_jdk_tarball_download_path: "{{ java_rv_jdk_tmp_dir }}/jdk-{{ java_rv_jdk_version }}_linux-{{ ansible_facts.architecture }}_bin.tar.gz"

java_rv_jdk_mvn_download_url: "https://dlcdn.apache.org/maven/maven-3/{{ java_rv_jdk_mvn_version }}/binaries/apache-maven-{{ java_rv_jdk_mvn_version }}-bin.tar.gz"
java_rv_jdk_mvn_tarball_download_path: "{{ java_rv_jdk_tmp_dir }}/apache-maven-{{ java_rv_jdk_mvn_version }}-bin.tar.gz"

java_rv_jdk_gradle_download_url: "https://downloads.gradle.org/distributions/gradle-{{ java_rv_jdk_gradle_version }}-all.zip"
java_rv_jdk_gradle_tmp_unzip_path: "{{ java_rv_jdk_tmp_dir }}"
java_rv_jdk_gradle_tarball_download_path: "{{ java_rv_jdk_tmp_dir }}/gradle-{{ java_rv_jdk_gradle_version }}-all.zip"

java_rv_jdk_groovy_download_url: "https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-sdk-{{ java_rv_jdk_groovy_version }}.zip"
java_rv_jdk_groovy_tmp_unzip_path: "{{ java_rv_jdk_tmp_dir }}"
java_rv_jdk_groovy_tarball_download_path: "{{ java_rv_jdk_tmp_dir }}/apache-groovy-sdk-{{ java_rv_jdk_groovy_version }}.zip"

java_rv_jdk_kotlinc_download_url: "https://github.com/JetBrains/kotlin/releases/download/v{{ java_rv_jdk_kotlinc_version }}/kotlin-compiler-{{ java_rv_jdk_kotlinc_version }}.zip"
java_rv_jdk_kotlinc_tarball_download_path: "{{ java_rv_jdk_tmp_dir }}/kotlin-compiler-{{ java_rv_jdk_kotlinc_version }}.zip"
