---
- name: Application User | Checking essential variables
  ansible.builtin.assert:
    that:
      - "{{ item }} is defined"
      - "{{ item }} != None"
    fail_msg: "{{ item }} is not defined, it should be present"
    success_msg: "{{ item }} is defined"
  with_items:
    - user_add_rv_username

- name: Application User | Setting Group Name
  ansible.builtin.set_fact:
    user_add_rv_user_primary_group: "{{ user_add_rv_username }}"
  when: >
    user_add_rv_user_primary_group is not defined
    or
    user_add_rv_user_primary_group | length < 1
