---
- name: Themes | Icon | vinceliuice Tela | Git Clone
  ansible.builtin.git:
    single_branch: true
    repo: "https://github.com/vinceliuice/Tela-icon-theme.git"
    dest: "{{ rv_themes_user_tmp_dir }}/vinceliuice-Tela-icon-theme"
    depth: 1
    version: master
  notify:
    - Themes | Icon | vinceliuice Tela | Install | Execute install script
    - Themes | Icon | vinceliuice Tela | Install | Result

- name: Themes | Icon | EliverLara Candy | Git clone
  ansible.builtin.git:
    single_branch: true
    repo: "https://github.com/EliverLara/candy-icons.git"
    dest: "{{ rv_themes_user_tmp_dir }}/EliverLara-candy-icons-git/"
    depth: 1
    version: master
  notify:
    - Themes | Icon | EliverLara Candy | Copy Resources | Copy icons
    - Themes | Icon | EliverLara Candy | Copy Resources | Delete git tracker from gtk directory

- name: Themes | Cursors | vinceliuice Layan-cursors | Git Clone
  ansible.builtin.git:
    single_branch: true
    repo: "https://github.com/vinceliuice/Layan-cursors.git"
    dest: "{{ rv_themes_user_tmp_dir }}/vinceliuice-Layan-cursors"
    depth: 1
    version: master
  notify:
    - Themes | Cursors | vinceliuice Layan-cursors | Install | Execute install script
    - Themes | Cursors | vinceliuice Layan-cursors | Install | Result

- name: Themes | Icon | Gvolpe BeautyLine | Git Clone
  ansible.builtin.git:
    single_branch: true
    repo: "https://github.com/gvolpe/BeautyLine.git"
    dest: "{{ rv_themes_user_tmp_dir }}/gvolpe-BeautyLine"
    depth: 1
    version: main
  notify: Themes | Icon | Gvolpe BeautyLine | Copy Resources | Copy icons
