---
- name: Themes |  Prerequisites | Fail if Root User
  ansible.builtin.command: whoami
  register: rl_sw_current_shelluser_shell_result
  failed_when: rl_sw_current_shelluser_shell_result.stdout == "root"
  changed_when: false

- name: Themes |  Prerequisites | Packages are present
  ansible.builtin.shell: "command -v {{ item }} >/dev/null 2>&1"
  changed_when: false
  with_items:
    - git
    - curl
    - wget
    - zip
    - tar
    - unzip
    - fc-cache
    - gtk-update-icon-cache

- name: Themes |  Prerequisites | Gather Facts
  ansible.builtin.setup:

- name: Themes |  Prerequisites | Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  with_items:
    - "{{ rv_themes_user_share_dir }}/applications"
    - "{{ rv_themes_user_share_dir }}/themes"
    - "{{ rv_themes_user_share_dir }}/plasma/desktoptheme"
    - "{{ rv_themes_user_share_dir }}/aurorae/themes"
    - "{{ rv_themes_user_share_dir }}/color-schemes"
    - "{{ rv_themes_user_share_dir }}/plasma/look-and-feel"
    - "{{ rv_themes_user_config_dir }}/Kvantum"
    - "{{ rv_themes_user_config_dir }}/konsave/profiles"
    - "{{ rv_themes_user_tmp_dir }}"
    - "{{ rv_themes_user_share_dir }}/konsole"
    - "{{ rv_themes_user_share_dir }}/fonts"
