---
- name: Themes | Terminal Themes | Download Bash-IT
  ansible.builtin.git:
    repo: "https://github.com/Bash-it/bash-it"
    dest: "{{ rv_themes_user_home_dir }}/.bash_it"
    depth: 1
    version: master

- name: Themes | Terminal Themes | Download Oh My ZSH
  ansible.builtin.git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ rv_themes_user_home_dir }}/.oh-my-zsh"
    depth: 1
    version: master

- name: Themes | Terminal Themes | Download fzf
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ rv_themes_user_home_dir }}/.fzf"
    depth: 1
    version: master
  notify:
    - Themes | Terminal Themes | Initialize fzf | Execute install script
    - Themes | Terminal Themes | Initialize fzf | Result

- name: Themes | Terminal Themes | Lookup ZSH_CUSTOM from env
  ansible.builtin.set_fact:
    pv_ua_user_zsh_custom_dir: "{{ lookup('env', 'ZSH_CUSTOM') }}"

- name: Themes | Terminal Themes | Set default ZSH_CUSTOM directory
  ansible.builtin.set_fact:
    pv_ua_user_zsh_custom_dir: "{{ rv_themes_user_home_dir }}/.oh-my-zsh/custom"
  when: pv_ua_user_zsh_custom_dir is undefined or pv_ua_user_zsh_custom_dir is none or (pv_ua_user_zsh_custom_dir | length == 0)

- name: Themes | Terminal Themes | Download zsh syntax highlighting
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ pv_ua_user_zsh_custom_dir }}/plugins/zsh-syntax-highlighting"
    depth: 1
    version: master

- name: Themes | Terminal Themes | Download zsh autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ pv_ua_user_zsh_custom_dir }}/plugins/zsh-autosuggestions"
    depth: 1
    version: master

- name: Themes | Terminal Themes | Download zsh completions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-completions"
    dest: "{{ pv_ua_user_zsh_custom_dir }}/plugins/zsh-completions"
    depth: 1
    version: master

- name: Themes | Terminal Themes | Download zsh powerlevel10k
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "{{ pv_ua_user_zsh_custom_dir }}/themes/powerlevel10k"
    depth: 1
    version: master
  notify:
    - Themes | Terminal Themes | Initialize p10k gitstatus | Execute install script
    - Themes | Terminal Themes | Initialize p10k gitstatus | Result
