---
- name: Golang | Prerequisites | Fail if Root User
  ansible.builtin.command: whoami
  register: rl_sw_current_shelluser_shell_result
  failed_when: rl_sw_current_shelluser_shell_result.stdout == "root"
  changed_when: false

- name: Golang | Prerequisites | Packages are present
  ansible.builtin.shell: "command -v {{ item }} >/dev/null 2>&1"
  changed_when: false
  with_items:
    - wget
    - tar

- name: Golang | Prerequisites | Gather Facts
  ansible.builtin.setup:
